add ArrayCache
open-orchestra/open-orchestra-base-api-bundle pull request #122
Opened 2017-06-13 14:05 UTC by itkg-nanne

2017-06-19 07:26 UTC, alavieille commented on BaseApi/Transformer/AbstractTransformer.php
> +        $isObject = is_object($mixed);
if isn't a object you can test here if not return $this->transform($mixed); and you can remove other if

2017-06-19 07:27 UTC, alavieille commented on BaseApi/Transformer/AbstractTransformer.php
> +    public function cacheTransform($mixed)
i m not sure is util to create a new method, may be refacto transformerManager

2017-06-26 07:46 UTC, itkg-nanne commented
update done, @alavieille

2017-06-26 07:46 UTC, itkg-nanne commented on BaseApi/Transformer/AbstractTransformer.php
> +    public function cacheTransform($mixed)
done as it to not BCBreak.

2017-06-30 07:42 UTC, alavieille approved these changes

2017-06-30 07:44 UTC, alavieille requested changes

2017-06-30 07:44 UTC, alavieille commented on BaseApi/Transformer/TransformerManager.php
> +    public function transform($name, $entity, $params = null) {
can you type params at an array ?

2017-07-03 14:00 UTC, itkg-nanne commented
update done @alavieille

2017-07-04 11:25 UTC, alavieille commented on BaseApi/Transformer/AbstractTransformer.php
> +    public function transform($mixed, array $params = null)
why null and not array()

2017-07-04 13:51 UTC, merged